image: python:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: cidemo

cache:
  paths:
  - ~/.cache/pip/

test:
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
  - pip install -r requirements/test.txt
  - python manage.py test
